### ISSUE TITLE
Benzinkanister

### ISSUE THREAD

**Issue by BOC0815** [nSystemz/nemesus-world-server#32]
Das benutzen des Benzinkanisters funktioniert nicht mehr, seit dem letzten Updates..

[OnUseInventory]: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at NemesusWorld.Controllers.ItemsController.OnUseInventory(Player player, String usage, Int32 itemid, Int32 amount, String selection) in C:\Users\Administrator\Desktop\RAGEMP Server\Server\NemesusWorld\backend\NemesusWorld\Controllers\ItemsController.cs:line 2083

**Comment by nSystemz** [comment]
Hi danke für die Meldung, Nach meinen aktuell Tests, geht der Benzinkanister. Es kann sein das du die alten Items löschen musst und einen neuen kaufen musst auf Grund der Änderungen in der Vergangenheit,

**Comment by BOC0815** [comment]
Wenn ich mir administrativ einen Kanister gebe, funktioniert der auch nicht, das ist normal?

**Comment by BOC0815** [comment]
Nach dem benutzen des Kanisters bleibt er mit einer rest Füllmenge im Inventar und ist nicht mehr benutzbar auch nicht dropbar.
